A = float(input("Digite o valor de A: "))
B = float(input("Digite o valor de B: "))
C = float(input("Digite o valor de C: "))
Delta = (B*B) - (4*A*C)
Yv= -(Delta)/ (4*A)
Xv = (-1 * B)/(2*A)
print("Valor do Xv: ", Xv)
print("Valor do Yv: ",Yv)
print("Valor do delta: ", Delta)